name: CI/CD

on: [push]

jobs:
  build:
    runs-on: amazonlinux2
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: Backend/hellopeople/to/mvn -B package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: Backend/target/*.jar
