name: ci-cd

on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run:  cd ../../
          - cd Backend/hellopeople
          - mvn package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          run: cd ../../
            - cd Backend/hellopeople
            - mvn test
          path: Backend/target/*.jar
